version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - FShopV2
  mongodb:
    container_name: mongo-dev
    image: mongo
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    networks:
      - FShopV2
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - '8081:8081'
    networks:
      - FShopV2
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - FShopV2 
      
networks:
  FShopV2:
    name: FShopV2-network